fileName = "include/index_html.h"


def generate_header_content():
    with open("mock-esp/public/index.html", "r") as file:
        html_content = file.read()
        return (
            '// This is an autogenerated file \n// DO NOT EDIT\n\n\n\n#ifndef INDEX_HTML_H\n#define INDEX_HTML_H\n\nconst String indexHtml = R"=====(\n'
            + html_content
            + '\n)=====";\n\n\n#endif'
        )


def update_template_header(content):
    with open(fileName, "w") as file:
        file.write(content)


# Generate header content
header_content = generate_header_content()

# Update template header file
update_template_header(header_content)

# Print a message indicating that the update was successful
print(fileName, " has been updated successfully.")
